
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Role: 'Role',
  Account: 'Account',
  Session: 'Session',
  User: 'User',
  VerificationToken: 'VerificationToken',
  PasswordResetToken: 'PasswordResetToken',
  UserApiKey: 'UserApiKey',
  Project: 'Project',
  Conversation: 'Conversation',
  Message: 'Message',
  Media: 'Media',
  GenJob: 'GenJob',
  Setting: 'Setting',
  PuterSession: 'PuterSession'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  level: 'level',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type RoleScalarFieldEnum = (typeof RoleScalarFieldEnum)[keyof typeof RoleScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  clerk_id: 'clerk_id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  password_hash: 'password_hash',
  avatar: 'avatar',
  role_id: 'role_id',
  email_verified_at: 'email_verified_at',
  last_login_at: 'last_login_at',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId',
  expires: 'expires',
  used: 'used',
  created_at: 'created_at'
} as const

export type PasswordResetTokenScalarFieldEnum = (typeof PasswordResetTokenScalarFieldEnum)[keyof typeof PasswordResetTokenScalarFieldEnum]


export const UserApiKeyScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  provider: 'provider',
  label: 'label',
  api_key: 'api_key',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserApiKeyScalarFieldEnum = (typeof UserApiKeyScalarFieldEnum)[keyof typeof UserApiKeyScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  description: 'description',
  emoji: 'emoji',
  color: 'color',
  system_prompt: 'system_prompt',
  is_pinned: 'is_pinned',
  is_archived: 'is_archived',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  project_id: 'project_id',
  title: 'title',
  provider: 'provider',
  model_id: 'model_id',
  skill: 'skill',
  is_starred: 'is_starred',
  is_pinned: 'is_pinned',
  is_archived: 'is_archived',
  total_tokens: 'total_tokens',
  last_message_at: 'last_message_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversation_id: 'conversation_id',
  role: 'role',
  content: 'content',
  model_id: 'model_id',
  tokens_used: 'tokens_used',
  is_error: 'is_error',
  created_at: 'created_at'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const MediaScalarFieldEnum = {
  id: 'id',
  message_id: 'message_id',
  bucket: 'bucket',
  object_key: 'object_key',
  url: 'url',
  type: 'type',
  filename: 'filename',
  original_filename: 'original_filename',
  size: 'size',
  mime_type: 'mime_type',
  width: 'width',
  height: 'height',
  duration: 'duration',
  gen_prompt: 'gen_prompt',
  gen_model_id: 'gen_model_id',
  gen_aspect_ratio: 'gen_aspect_ratio',
  gen_quality: 'gen_quality',
  gen_duration: 'gen_duration',
  gen_fps: 'gen_fps',
  gen_resolution: 'gen_resolution',
  is_generated: 'is_generated',
  created_at: 'created_at'
} as const

export type MediaScalarFieldEnum = (typeof MediaScalarFieldEnum)[keyof typeof MediaScalarFieldEnum]


export const GenJobScalarFieldEnum = {
  id: 'id',
  conversation_id: 'conversation_id',
  message_id: 'message_id',
  job_type: 'job_type',
  status: 'status',
  provider: 'provider',
  model_id: 'model_id',
  prompt: 'prompt',
  aspect_ratio: 'aspect_ratio',
  quality: 'quality',
  duration: 'duration',
  fps: 'fps',
  resolution: 'resolution',
  extend_from_media_id: 'extend_from_media_id',
  extend_from_url: 'extend_from_url',
  extend_start_sec: 'extend_start_sec',
  result_url: 'result_url',
  result_media_id: 'result_media_id',
  error_message: 'error_message',
  progress: 'progress',
  started_at: 'started_at',
  completed_at: 'completed_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type GenJobScalarFieldEnum = (typeof GenJobScalarFieldEnum)[keyof typeof GenJobScalarFieldEnum]


export const SettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  group_name: 'group_name',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type SettingScalarFieldEnum = (typeof SettingScalarFieldEnum)[keyof typeof SettingScalarFieldEnum]


export const PuterSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  token: 'token',
  puter_username: 'puter_username',
  puter_uid: 'puter_uid',
  app_uid: 'app_uid',
  is_valid: 'is_valid',
  validated_at: 'validated_at',
  expires_at: 'expires_at',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type PuterSessionScalarFieldEnum = (typeof PuterSessionScalarFieldEnum)[keyof typeof PuterSessionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

