
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GenJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GenJob
 * 
 */
export type GenJobModel = runtime.Types.Result.DefaultSelection<Prisma.$GenJobPayload>

export type AggregateGenJob = {
  _count: GenJobCountAggregateOutputType | null
  _avg: GenJobAvgAggregateOutputType | null
  _sum: GenJobSumAggregateOutputType | null
  _min: GenJobMinAggregateOutputType | null
  _max: GenJobMaxAggregateOutputType | null
}

export type GenJobAvgAggregateOutputType = {
  duration: number | null
  fps: number | null
  extend_start_sec: number | null
  progress: number | null
}

export type GenJobSumAggregateOutputType = {
  duration: number | null
  fps: number | null
  extend_start_sec: number | null
  progress: number | null
}

export type GenJobMinAggregateOutputType = {
  id: string | null
  conversation_id: string | null
  message_id: string | null
  job_type: $Enums.AISkill | null
  status: $Enums.GenJobStatus | null
  provider: string | null
  model_id: string | null
  prompt: string | null
  aspect_ratio: string | null
  quality: string | null
  duration: number | null
  fps: number | null
  resolution: string | null
  extend_from_media_id: string | null
  extend_from_url: string | null
  extend_start_sec: number | null
  result_url: string | null
  result_media_id: string | null
  error_message: string | null
  progress: number | null
  started_at: Date | null
  completed_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type GenJobMaxAggregateOutputType = {
  id: string | null
  conversation_id: string | null
  message_id: string | null
  job_type: $Enums.AISkill | null
  status: $Enums.GenJobStatus | null
  provider: string | null
  model_id: string | null
  prompt: string | null
  aspect_ratio: string | null
  quality: string | null
  duration: number | null
  fps: number | null
  resolution: string | null
  extend_from_media_id: string | null
  extend_from_url: string | null
  extend_start_sec: number | null
  result_url: string | null
  result_media_id: string | null
  error_message: string | null
  progress: number | null
  started_at: Date | null
  completed_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type GenJobCountAggregateOutputType = {
  id: number
  conversation_id: number
  message_id: number
  job_type: number
  status: number
  provider: number
  model_id: number
  prompt: number
  aspect_ratio: number
  quality: number
  duration: number
  fps: number
  resolution: number
  extend_from_media_id: number
  extend_from_url: number
  extend_start_sec: number
  result_url: number
  result_media_id: number
  error_message: number
  progress: number
  started_at: number
  completed_at: number
  created_at: number
  updated_at: number
  _all: number
}


export type GenJobAvgAggregateInputType = {
  duration?: true
  fps?: true
  extend_start_sec?: true
  progress?: true
}

export type GenJobSumAggregateInputType = {
  duration?: true
  fps?: true
  extend_start_sec?: true
  progress?: true
}

export type GenJobMinAggregateInputType = {
  id?: true
  conversation_id?: true
  message_id?: true
  job_type?: true
  status?: true
  provider?: true
  model_id?: true
  prompt?: true
  aspect_ratio?: true
  quality?: true
  duration?: true
  fps?: true
  resolution?: true
  extend_from_media_id?: true
  extend_from_url?: true
  extend_start_sec?: true
  result_url?: true
  result_media_id?: true
  error_message?: true
  progress?: true
  started_at?: true
  completed_at?: true
  created_at?: true
  updated_at?: true
}

export type GenJobMaxAggregateInputType = {
  id?: true
  conversation_id?: true
  message_id?: true
  job_type?: true
  status?: true
  provider?: true
  model_id?: true
  prompt?: true
  aspect_ratio?: true
  quality?: true
  duration?: true
  fps?: true
  resolution?: true
  extend_from_media_id?: true
  extend_from_url?: true
  extend_start_sec?: true
  result_url?: true
  result_media_id?: true
  error_message?: true
  progress?: true
  started_at?: true
  completed_at?: true
  created_at?: true
  updated_at?: true
}

export type GenJobCountAggregateInputType = {
  id?: true
  conversation_id?: true
  message_id?: true
  job_type?: true
  status?: true
  provider?: true
  model_id?: true
  prompt?: true
  aspect_ratio?: true
  quality?: true
  duration?: true
  fps?: true
  resolution?: true
  extend_from_media_id?: true
  extend_from_url?: true
  extend_start_sec?: true
  result_url?: true
  result_media_id?: true
  error_message?: true
  progress?: true
  started_at?: true
  completed_at?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type GenJobAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GenJob to aggregate.
   */
  where?: Prisma.GenJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GenJobs to fetch.
   */
  orderBy?: Prisma.GenJobOrderByWithRelationInput | Prisma.GenJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GenJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GenJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GenJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GenJobs
  **/
  _count?: true | GenJobCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GenJobAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GenJobSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GenJobMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GenJobMaxAggregateInputType
}

export type GetGenJobAggregateType<T extends GenJobAggregateArgs> = {
      [P in keyof T & keyof AggregateGenJob]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGenJob[P]>
    : Prisma.GetScalarType<T[P], AggregateGenJob[P]>
}




export type GenJobGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GenJobWhereInput
  orderBy?: Prisma.GenJobOrderByWithAggregationInput | Prisma.GenJobOrderByWithAggregationInput[]
  by: Prisma.GenJobScalarFieldEnum[] | Prisma.GenJobScalarFieldEnum
  having?: Prisma.GenJobScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GenJobCountAggregateInputType | true
  _avg?: GenJobAvgAggregateInputType
  _sum?: GenJobSumAggregateInputType
  _min?: GenJobMinAggregateInputType
  _max?: GenJobMaxAggregateInputType
}

export type GenJobGroupByOutputType = {
  id: string
  conversation_id: string
  message_id: string | null
  job_type: $Enums.AISkill
  status: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio: string | null
  quality: string | null
  duration: number | null
  fps: number | null
  resolution: string | null
  extend_from_media_id: string | null
  extend_from_url: string | null
  extend_start_sec: number | null
  result_url: string | null
  result_media_id: string | null
  error_message: string | null
  progress: number
  started_at: Date | null
  completed_at: Date | null
  created_at: Date
  updated_at: Date
  _count: GenJobCountAggregateOutputType | null
  _avg: GenJobAvgAggregateOutputType | null
  _sum: GenJobSumAggregateOutputType | null
  _min: GenJobMinAggregateOutputType | null
  _max: GenJobMaxAggregateOutputType | null
}

export type GetGenJobGroupByPayload<T extends GenJobGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GenJobGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GenJobGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GenJobGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GenJobGroupByOutputType[P]>
      }
    >
  >



export type GenJobWhereInput = {
  AND?: Prisma.GenJobWhereInput | Prisma.GenJobWhereInput[]
  OR?: Prisma.GenJobWhereInput[]
  NOT?: Prisma.GenJobWhereInput | Prisma.GenJobWhereInput[]
  id?: Prisma.StringFilter<"GenJob"> | string
  conversation_id?: Prisma.StringFilter<"GenJob"> | string
  message_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  job_type?: Prisma.EnumAISkillFilter<"GenJob"> | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFilter<"GenJob"> | $Enums.GenJobStatus
  provider?: Prisma.StringFilter<"GenJob"> | string
  model_id?: Prisma.StringFilter<"GenJob"> | string
  prompt?: Prisma.StringFilter<"GenJob"> | string
  aspect_ratio?: Prisma.StringNullableFilter<"GenJob"> | string | null
  quality?: Prisma.StringNullableFilter<"GenJob"> | string | null
  duration?: Prisma.IntNullableFilter<"GenJob"> | number | null
  fps?: Prisma.IntNullableFilter<"GenJob"> | number | null
  resolution?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_start_sec?: Prisma.FloatNullableFilter<"GenJob"> | number | null
  result_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  result_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  error_message?: Prisma.StringNullableFilter<"GenJob"> | string | null
  progress?: Prisma.IntFilter<"GenJob"> | number
  started_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  completed_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
  conversation?: Prisma.XOR<Prisma.ConversationScalarRelationFilter, Prisma.ConversationWhereInput>
  message?: Prisma.XOR<Prisma.MessageNullableScalarRelationFilter, Prisma.MessageWhereInput> | null
}

export type GenJobOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  message_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  aspect_ratio?: Prisma.SortOrderInput | Prisma.SortOrder
  quality?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  fps?: Prisma.SortOrderInput | Prisma.SortOrder
  resolution?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_from_media_id?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_from_url?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrderInput | Prisma.SortOrder
  result_url?: Prisma.SortOrderInput | Prisma.SortOrder
  result_media_id?: Prisma.SortOrderInput | Prisma.SortOrder
  error_message?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  started_at?: Prisma.SortOrderInput | Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  conversation?: Prisma.ConversationOrderByWithRelationInput
  message?: Prisma.MessageOrderByWithRelationInput
}

export type GenJobWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GenJobWhereInput | Prisma.GenJobWhereInput[]
  OR?: Prisma.GenJobWhereInput[]
  NOT?: Prisma.GenJobWhereInput | Prisma.GenJobWhereInput[]
  conversation_id?: Prisma.StringFilter<"GenJob"> | string
  message_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  job_type?: Prisma.EnumAISkillFilter<"GenJob"> | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFilter<"GenJob"> | $Enums.GenJobStatus
  provider?: Prisma.StringFilter<"GenJob"> | string
  model_id?: Prisma.StringFilter<"GenJob"> | string
  prompt?: Prisma.StringFilter<"GenJob"> | string
  aspect_ratio?: Prisma.StringNullableFilter<"GenJob"> | string | null
  quality?: Prisma.StringNullableFilter<"GenJob"> | string | null
  duration?: Prisma.IntNullableFilter<"GenJob"> | number | null
  fps?: Prisma.IntNullableFilter<"GenJob"> | number | null
  resolution?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_start_sec?: Prisma.FloatNullableFilter<"GenJob"> | number | null
  result_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  result_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  error_message?: Prisma.StringNullableFilter<"GenJob"> | string | null
  progress?: Prisma.IntFilter<"GenJob"> | number
  started_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  completed_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
  conversation?: Prisma.XOR<Prisma.ConversationScalarRelationFilter, Prisma.ConversationWhereInput>
  message?: Prisma.XOR<Prisma.MessageNullableScalarRelationFilter, Prisma.MessageWhereInput> | null
}, "id">

export type GenJobOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  message_id?: Prisma.SortOrderInput | Prisma.SortOrder
  job_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  aspect_ratio?: Prisma.SortOrderInput | Prisma.SortOrder
  quality?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  fps?: Prisma.SortOrderInput | Prisma.SortOrder
  resolution?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_from_media_id?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_from_url?: Prisma.SortOrderInput | Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrderInput | Prisma.SortOrder
  result_url?: Prisma.SortOrderInput | Prisma.SortOrder
  result_media_id?: Prisma.SortOrderInput | Prisma.SortOrder
  error_message?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  started_at?: Prisma.SortOrderInput | Prisma.SortOrder
  completed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.GenJobCountOrderByAggregateInput
  _avg?: Prisma.GenJobAvgOrderByAggregateInput
  _max?: Prisma.GenJobMaxOrderByAggregateInput
  _min?: Prisma.GenJobMinOrderByAggregateInput
  _sum?: Prisma.GenJobSumOrderByAggregateInput
}

export type GenJobScalarWhereWithAggregatesInput = {
  AND?: Prisma.GenJobScalarWhereWithAggregatesInput | Prisma.GenJobScalarWhereWithAggregatesInput[]
  OR?: Prisma.GenJobScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GenJobScalarWhereWithAggregatesInput | Prisma.GenJobScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GenJob"> | string
  conversation_id?: Prisma.StringWithAggregatesFilter<"GenJob"> | string
  message_id?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  job_type?: Prisma.EnumAISkillWithAggregatesFilter<"GenJob"> | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusWithAggregatesFilter<"GenJob"> | $Enums.GenJobStatus
  provider?: Prisma.StringWithAggregatesFilter<"GenJob"> | string
  model_id?: Prisma.StringWithAggregatesFilter<"GenJob"> | string
  prompt?: Prisma.StringWithAggregatesFilter<"GenJob"> | string
  aspect_ratio?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  quality?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  duration?: Prisma.IntNullableWithAggregatesFilter<"GenJob"> | number | null
  fps?: Prisma.IntNullableWithAggregatesFilter<"GenJob"> | number | null
  resolution?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  extend_from_media_id?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  extend_from_url?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  extend_start_sec?: Prisma.FloatNullableWithAggregatesFilter<"GenJob"> | number | null
  result_url?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  result_media_id?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  error_message?: Prisma.StringNullableWithAggregatesFilter<"GenJob"> | string | null
  progress?: Prisma.IntWithAggregatesFilter<"GenJob"> | number
  started_at?: Prisma.DateTimeNullableWithAggregatesFilter<"GenJob"> | Date | string | null
  completed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"GenJob"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"GenJob"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"GenJob"> | Date | string
}

export type GenJobCreateInput = {
  id?: string
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  conversation: Prisma.ConversationCreateNestedOneWithoutGen_jobsInput
  message?: Prisma.MessageCreateNestedOneWithoutGen_jobsInput
}

export type GenJobUncheckedCreateInput = {
  id?: string
  conversation_id: string
  message_id?: string | null
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  conversation?: Prisma.ConversationUpdateOneRequiredWithoutGen_jobsNestedInput
  message?: Prisma.MessageUpdateOneWithoutGen_jobsNestedInput
}

export type GenJobUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  message_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobCreateManyInput = {
  id?: string
  conversation_id: string
  message_id?: string | null
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  message_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobListRelationFilter = {
  every?: Prisma.GenJobWhereInput
  some?: Prisma.GenJobWhereInput
  none?: Prisma.GenJobWhereInput
}

export type GenJobOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GenJobCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  message_id?: Prisma.SortOrder
  job_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  aspect_ratio?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  fps?: Prisma.SortOrder
  resolution?: Prisma.SortOrder
  extend_from_media_id?: Prisma.SortOrder
  extend_from_url?: Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrder
  result_url?: Prisma.SortOrder
  result_media_id?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type GenJobAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  fps?: Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type GenJobMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  message_id?: Prisma.SortOrder
  job_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  aspect_ratio?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  fps?: Prisma.SortOrder
  resolution?: Prisma.SortOrder
  extend_from_media_id?: Prisma.SortOrder
  extend_from_url?: Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrder
  result_url?: Prisma.SortOrder
  result_media_id?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type GenJobMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversation_id?: Prisma.SortOrder
  message_id?: Prisma.SortOrder
  job_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  model_id?: Prisma.SortOrder
  prompt?: Prisma.SortOrder
  aspect_ratio?: Prisma.SortOrder
  quality?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  fps?: Prisma.SortOrder
  resolution?: Prisma.SortOrder
  extend_from_media_id?: Prisma.SortOrder
  extend_from_url?: Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrder
  result_url?: Prisma.SortOrder
  result_media_id?: Prisma.SortOrder
  error_message?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  started_at?: Prisma.SortOrder
  completed_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type GenJobSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  fps?: Prisma.SortOrder
  extend_start_sec?: Prisma.SortOrder
  progress?: Prisma.SortOrder
}

export type GenJobCreateNestedManyWithoutConversationInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput> | Prisma.GenJobCreateWithoutConversationInput[] | Prisma.GenJobUncheckedCreateWithoutConversationInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutConversationInput | Prisma.GenJobCreateOrConnectWithoutConversationInput[]
  createMany?: Prisma.GenJobCreateManyConversationInputEnvelope
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
}

export type GenJobUncheckedCreateNestedManyWithoutConversationInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput> | Prisma.GenJobCreateWithoutConversationInput[] | Prisma.GenJobUncheckedCreateWithoutConversationInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutConversationInput | Prisma.GenJobCreateOrConnectWithoutConversationInput[]
  createMany?: Prisma.GenJobCreateManyConversationInputEnvelope
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
}

export type GenJobUpdateManyWithoutConversationNestedInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput> | Prisma.GenJobCreateWithoutConversationInput[] | Prisma.GenJobUncheckedCreateWithoutConversationInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutConversationInput | Prisma.GenJobCreateOrConnectWithoutConversationInput[]
  upsert?: Prisma.GenJobUpsertWithWhereUniqueWithoutConversationInput | Prisma.GenJobUpsertWithWhereUniqueWithoutConversationInput[]
  createMany?: Prisma.GenJobCreateManyConversationInputEnvelope
  set?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  disconnect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  delete?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  update?: Prisma.GenJobUpdateWithWhereUniqueWithoutConversationInput | Prisma.GenJobUpdateWithWhereUniqueWithoutConversationInput[]
  updateMany?: Prisma.GenJobUpdateManyWithWhereWithoutConversationInput | Prisma.GenJobUpdateManyWithWhereWithoutConversationInput[]
  deleteMany?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
}

export type GenJobUncheckedUpdateManyWithoutConversationNestedInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput> | Prisma.GenJobCreateWithoutConversationInput[] | Prisma.GenJobUncheckedCreateWithoutConversationInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutConversationInput | Prisma.GenJobCreateOrConnectWithoutConversationInput[]
  upsert?: Prisma.GenJobUpsertWithWhereUniqueWithoutConversationInput | Prisma.GenJobUpsertWithWhereUniqueWithoutConversationInput[]
  createMany?: Prisma.GenJobCreateManyConversationInputEnvelope
  set?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  disconnect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  delete?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  update?: Prisma.GenJobUpdateWithWhereUniqueWithoutConversationInput | Prisma.GenJobUpdateWithWhereUniqueWithoutConversationInput[]
  updateMany?: Prisma.GenJobUpdateManyWithWhereWithoutConversationInput | Prisma.GenJobUpdateManyWithWhereWithoutConversationInput[]
  deleteMany?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
}

export type GenJobCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput> | Prisma.GenJobCreateWithoutMessageInput[] | Prisma.GenJobUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutMessageInput | Prisma.GenJobCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.GenJobCreateManyMessageInputEnvelope
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
}

export type GenJobUncheckedCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput> | Prisma.GenJobCreateWithoutMessageInput[] | Prisma.GenJobUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutMessageInput | Prisma.GenJobCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.GenJobCreateManyMessageInputEnvelope
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
}

export type GenJobUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput> | Prisma.GenJobCreateWithoutMessageInput[] | Prisma.GenJobUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutMessageInput | Prisma.GenJobCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.GenJobUpsertWithWhereUniqueWithoutMessageInput | Prisma.GenJobUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.GenJobCreateManyMessageInputEnvelope
  set?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  disconnect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  delete?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  update?: Prisma.GenJobUpdateWithWhereUniqueWithoutMessageInput | Prisma.GenJobUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.GenJobUpdateManyWithWhereWithoutMessageInput | Prisma.GenJobUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
}

export type GenJobUncheckedUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput> | Prisma.GenJobCreateWithoutMessageInput[] | Prisma.GenJobUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.GenJobCreateOrConnectWithoutMessageInput | Prisma.GenJobCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.GenJobUpsertWithWhereUniqueWithoutMessageInput | Prisma.GenJobUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.GenJobCreateManyMessageInputEnvelope
  set?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  disconnect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  delete?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  connect?: Prisma.GenJobWhereUniqueInput | Prisma.GenJobWhereUniqueInput[]
  update?: Prisma.GenJobUpdateWithWhereUniqueWithoutMessageInput | Prisma.GenJobUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.GenJobUpdateManyWithWhereWithoutMessageInput | Prisma.GenJobUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
}

export type EnumGenJobStatusFieldUpdateOperationsInput = {
  set?: $Enums.GenJobStatus
}

export type GenJobCreateWithoutConversationInput = {
  id?: string
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  message?: Prisma.MessageCreateNestedOneWithoutGen_jobsInput
}

export type GenJobUncheckedCreateWithoutConversationInput = {
  id?: string
  message_id?: string | null
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobCreateOrConnectWithoutConversationInput = {
  where: Prisma.GenJobWhereUniqueInput
  create: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput>
}

export type GenJobCreateManyConversationInputEnvelope = {
  data: Prisma.GenJobCreateManyConversationInput | Prisma.GenJobCreateManyConversationInput[]
  skipDuplicates?: boolean
}

export type GenJobUpsertWithWhereUniqueWithoutConversationInput = {
  where: Prisma.GenJobWhereUniqueInput
  update: Prisma.XOR<Prisma.GenJobUpdateWithoutConversationInput, Prisma.GenJobUncheckedUpdateWithoutConversationInput>
  create: Prisma.XOR<Prisma.GenJobCreateWithoutConversationInput, Prisma.GenJobUncheckedCreateWithoutConversationInput>
}

export type GenJobUpdateWithWhereUniqueWithoutConversationInput = {
  where: Prisma.GenJobWhereUniqueInput
  data: Prisma.XOR<Prisma.GenJobUpdateWithoutConversationInput, Prisma.GenJobUncheckedUpdateWithoutConversationInput>
}

export type GenJobUpdateManyWithWhereWithoutConversationInput = {
  where: Prisma.GenJobScalarWhereInput
  data: Prisma.XOR<Prisma.GenJobUpdateManyMutationInput, Prisma.GenJobUncheckedUpdateManyWithoutConversationInput>
}

export type GenJobScalarWhereInput = {
  AND?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
  OR?: Prisma.GenJobScalarWhereInput[]
  NOT?: Prisma.GenJobScalarWhereInput | Prisma.GenJobScalarWhereInput[]
  id?: Prisma.StringFilter<"GenJob"> | string
  conversation_id?: Prisma.StringFilter<"GenJob"> | string
  message_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  job_type?: Prisma.EnumAISkillFilter<"GenJob"> | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFilter<"GenJob"> | $Enums.GenJobStatus
  provider?: Prisma.StringFilter<"GenJob"> | string
  model_id?: Prisma.StringFilter<"GenJob"> | string
  prompt?: Prisma.StringFilter<"GenJob"> | string
  aspect_ratio?: Prisma.StringNullableFilter<"GenJob"> | string | null
  quality?: Prisma.StringNullableFilter<"GenJob"> | string | null
  duration?: Prisma.IntNullableFilter<"GenJob"> | number | null
  fps?: Prisma.IntNullableFilter<"GenJob"> | number | null
  resolution?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_from_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  extend_start_sec?: Prisma.FloatNullableFilter<"GenJob"> | number | null
  result_url?: Prisma.StringNullableFilter<"GenJob"> | string | null
  result_media_id?: Prisma.StringNullableFilter<"GenJob"> | string | null
  error_message?: Prisma.StringNullableFilter<"GenJob"> | string | null
  progress?: Prisma.IntFilter<"GenJob"> | number
  started_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  completed_at?: Prisma.DateTimeNullableFilter<"GenJob"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"GenJob"> | Date | string
}

export type GenJobCreateWithoutMessageInput = {
  id?: string
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  conversation: Prisma.ConversationCreateNestedOneWithoutGen_jobsInput
}

export type GenJobUncheckedCreateWithoutMessageInput = {
  id?: string
  conversation_id: string
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobCreateOrConnectWithoutMessageInput = {
  where: Prisma.GenJobWhereUniqueInput
  create: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput>
}

export type GenJobCreateManyMessageInputEnvelope = {
  data: Prisma.GenJobCreateManyMessageInput | Prisma.GenJobCreateManyMessageInput[]
  skipDuplicates?: boolean
}

export type GenJobUpsertWithWhereUniqueWithoutMessageInput = {
  where: Prisma.GenJobWhereUniqueInput
  update: Prisma.XOR<Prisma.GenJobUpdateWithoutMessageInput, Prisma.GenJobUncheckedUpdateWithoutMessageInput>
  create: Prisma.XOR<Prisma.GenJobCreateWithoutMessageInput, Prisma.GenJobUncheckedCreateWithoutMessageInput>
}

export type GenJobUpdateWithWhereUniqueWithoutMessageInput = {
  where: Prisma.GenJobWhereUniqueInput
  data: Prisma.XOR<Prisma.GenJobUpdateWithoutMessageInput, Prisma.GenJobUncheckedUpdateWithoutMessageInput>
}

export type GenJobUpdateManyWithWhereWithoutMessageInput = {
  where: Prisma.GenJobScalarWhereInput
  data: Prisma.XOR<Prisma.GenJobUpdateManyMutationInput, Prisma.GenJobUncheckedUpdateManyWithoutMessageInput>
}

export type GenJobCreateManyConversationInput = {
  id?: string
  message_id?: string | null
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobUpdateWithoutConversationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.MessageUpdateOneWithoutGen_jobsNestedInput
}

export type GenJobUncheckedUpdateWithoutConversationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobUncheckedUpdateManyWithoutConversationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobCreateManyMessageInput = {
  id?: string
  conversation_id: string
  job_type: $Enums.AISkill
  status?: $Enums.GenJobStatus
  provider: string
  model_id: string
  prompt: string
  aspect_ratio?: string | null
  quality?: string | null
  duration?: number | null
  fps?: number | null
  resolution?: string | null
  extend_from_media_id?: string | null
  extend_from_url?: string | null
  extend_start_sec?: number | null
  result_url?: string | null
  result_media_id?: string | null
  error_message?: string | null
  progress?: number
  started_at?: Date | string | null
  completed_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type GenJobUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  conversation?: Prisma.ConversationUpdateOneRequiredWithoutGen_jobsNestedInput
}

export type GenJobUncheckedUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GenJobUncheckedUpdateManyWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversation_id?: Prisma.StringFieldUpdateOperationsInput | string
  job_type?: Prisma.EnumAISkillFieldUpdateOperationsInput | $Enums.AISkill
  status?: Prisma.EnumGenJobStatusFieldUpdateOperationsInput | $Enums.GenJobStatus
  provider?: Prisma.StringFieldUpdateOperationsInput | string
  model_id?: Prisma.StringFieldUpdateOperationsInput | string
  prompt?: Prisma.StringFieldUpdateOperationsInput | string
  aspect_ratio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quality?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fps?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resolution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_from_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  extend_start_sec?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  result_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result_media_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error_message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  started_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type GenJobSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  message_id?: boolean
  job_type?: boolean
  status?: boolean
  provider?: boolean
  model_id?: boolean
  prompt?: boolean
  aspect_ratio?: boolean
  quality?: boolean
  duration?: boolean
  fps?: boolean
  resolution?: boolean
  extend_from_media_id?: boolean
  extend_from_url?: boolean
  extend_start_sec?: boolean
  result_url?: boolean
  result_media_id?: boolean
  error_message?: boolean
  progress?: boolean
  started_at?: boolean
  completed_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}, ExtArgs["result"]["genJob"]>

export type GenJobSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  message_id?: boolean
  job_type?: boolean
  status?: boolean
  provider?: boolean
  model_id?: boolean
  prompt?: boolean
  aspect_ratio?: boolean
  quality?: boolean
  duration?: boolean
  fps?: boolean
  resolution?: boolean
  extend_from_media_id?: boolean
  extend_from_url?: boolean
  extend_start_sec?: boolean
  result_url?: boolean
  result_media_id?: boolean
  error_message?: boolean
  progress?: boolean
  started_at?: boolean
  completed_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}, ExtArgs["result"]["genJob"]>

export type GenJobSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversation_id?: boolean
  message_id?: boolean
  job_type?: boolean
  status?: boolean
  provider?: boolean
  model_id?: boolean
  prompt?: boolean
  aspect_ratio?: boolean
  quality?: boolean
  duration?: boolean
  fps?: boolean
  resolution?: boolean
  extend_from_media_id?: boolean
  extend_from_url?: boolean
  extend_start_sec?: boolean
  result_url?: boolean
  result_media_id?: boolean
  error_message?: boolean
  progress?: boolean
  started_at?: boolean
  completed_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}, ExtArgs["result"]["genJob"]>

export type GenJobSelectScalar = {
  id?: boolean
  conversation_id?: boolean
  message_id?: boolean
  job_type?: boolean
  status?: boolean
  provider?: boolean
  model_id?: boolean
  prompt?: boolean
  aspect_ratio?: boolean
  quality?: boolean
  duration?: boolean
  fps?: boolean
  resolution?: boolean
  extend_from_media_id?: boolean
  extend_from_url?: boolean
  extend_start_sec?: boolean
  result_url?: boolean
  result_media_id?: boolean
  error_message?: boolean
  progress?: boolean
  started_at?: boolean
  completed_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type GenJobOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "conversation_id" | "message_id" | "job_type" | "status" | "provider" | "model_id" | "prompt" | "aspect_ratio" | "quality" | "duration" | "fps" | "resolution" | "extend_from_media_id" | "extend_from_url" | "extend_start_sec" | "result_url" | "result_media_id" | "error_message" | "progress" | "started_at" | "completed_at" | "created_at" | "updated_at", ExtArgs["result"]["genJob"]>
export type GenJobInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}
export type GenJobIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}
export type GenJobIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  conversation?: boolean | Prisma.ConversationDefaultArgs<ExtArgs>
  message?: boolean | Prisma.GenJob$messageArgs<ExtArgs>
}

export type $GenJobPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GenJob"
  objects: {
    conversation: Prisma.$ConversationPayload<ExtArgs>
    message: Prisma.$MessagePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    conversation_id: string
    message_id: string | null
    job_type: $Enums.AISkill
    status: $Enums.GenJobStatus
    provider: string
    model_id: string
    prompt: string
    /**
     * Rasio aspek gambar — pilihan: "1:1" | "16:9" | "9:16" | "4:3" | "3:4" | "2:3" | "3:2" | "21:9"
     */
    aspect_ratio: string | null
    /**
     * Kualitas/resolusi output — pilihan: "512" | "1K" | "2K" | "4K"
     */
    quality: string | null
    /**
     * Durasi video dalam detik — pilihan: 5 | 10 | 15 | 30
     */
    duration: number | null
    /**
     * Frame per second — pilihan: 24 | 30 | 60
     */
    fps: number | null
    /**
     * Resolusi video — pilihan: "720p" | "1080p" | "4K"
     */
    resolution: string | null
    /**
     * ID Media dari video yang akan di-extend (untuk fitur "Extend Video")
     */
    extend_from_media_id: string | null
    /**
     * URL sumber video yang di-extend (bisa dari MinIO)
     */
    extend_from_url: string | null
    /**
     * Detik mulai extend (e.g. dari detik ke-8 dari video 10 detik)
     */
    extend_start_sec: number | null
    result_url: string | null
    result_media_id: string | null
    error_message: string | null
    /**
     * Progress 0–100, update via Redis pub/sub → SSE ke client
     */
    progress: number
    started_at: Date | null
    completed_at: Date | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["genJob"]>
  composites: {}
}

export type GenJobGetPayload<S extends boolean | null | undefined | GenJobDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GenJobPayload, S>

export type GenJobCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GenJobFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GenJobCountAggregateInputType | true
  }

export interface GenJobDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GenJob'], meta: { name: 'GenJob' } }
  /**
   * Find zero or one GenJob that matches the filter.
   * @param {GenJobFindUniqueArgs} args - Arguments to find a GenJob
   * @example
   * // Get one GenJob
   * const genJob = await prisma.genJob.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GenJobFindUniqueArgs>(args: Prisma.SelectSubset<T, GenJobFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GenJob that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GenJobFindUniqueOrThrowArgs} args - Arguments to find a GenJob
   * @example
   * // Get one GenJob
   * const genJob = await prisma.genJob.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GenJobFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GenJobFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GenJob that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobFindFirstArgs} args - Arguments to find a GenJob
   * @example
   * // Get one GenJob
   * const genJob = await prisma.genJob.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GenJobFindFirstArgs>(args?: Prisma.SelectSubset<T, GenJobFindFirstArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GenJob that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobFindFirstOrThrowArgs} args - Arguments to find a GenJob
   * @example
   * // Get one GenJob
   * const genJob = await prisma.genJob.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GenJobFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GenJobFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GenJobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GenJobs
   * const genJobs = await prisma.genJob.findMany()
   * 
   * // Get first 10 GenJobs
   * const genJobs = await prisma.genJob.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const genJobWithIdOnly = await prisma.genJob.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GenJobFindManyArgs>(args?: Prisma.SelectSubset<T, GenJobFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GenJob.
   * @param {GenJobCreateArgs} args - Arguments to create a GenJob.
   * @example
   * // Create one GenJob
   * const GenJob = await prisma.genJob.create({
   *   data: {
   *     // ... data to create a GenJob
   *   }
   * })
   * 
   */
  create<T extends GenJobCreateArgs>(args: Prisma.SelectSubset<T, GenJobCreateArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GenJobs.
   * @param {GenJobCreateManyArgs} args - Arguments to create many GenJobs.
   * @example
   * // Create many GenJobs
   * const genJob = await prisma.genJob.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GenJobCreateManyArgs>(args?: Prisma.SelectSubset<T, GenJobCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GenJobs and returns the data saved in the database.
   * @param {GenJobCreateManyAndReturnArgs} args - Arguments to create many GenJobs.
   * @example
   * // Create many GenJobs
   * const genJob = await prisma.genJob.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GenJobs and only return the `id`
   * const genJobWithIdOnly = await prisma.genJob.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GenJobCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GenJobCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GenJob.
   * @param {GenJobDeleteArgs} args - Arguments to delete one GenJob.
   * @example
   * // Delete one GenJob
   * const GenJob = await prisma.genJob.delete({
   *   where: {
   *     // ... filter to delete one GenJob
   *   }
   * })
   * 
   */
  delete<T extends GenJobDeleteArgs>(args: Prisma.SelectSubset<T, GenJobDeleteArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GenJob.
   * @param {GenJobUpdateArgs} args - Arguments to update one GenJob.
   * @example
   * // Update one GenJob
   * const genJob = await prisma.genJob.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GenJobUpdateArgs>(args: Prisma.SelectSubset<T, GenJobUpdateArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GenJobs.
   * @param {GenJobDeleteManyArgs} args - Arguments to filter GenJobs to delete.
   * @example
   * // Delete a few GenJobs
   * const { count } = await prisma.genJob.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GenJobDeleteManyArgs>(args?: Prisma.SelectSubset<T, GenJobDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GenJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GenJobs
   * const genJob = await prisma.genJob.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GenJobUpdateManyArgs>(args: Prisma.SelectSubset<T, GenJobUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GenJobs and returns the data updated in the database.
   * @param {GenJobUpdateManyAndReturnArgs} args - Arguments to update many GenJobs.
   * @example
   * // Update many GenJobs
   * const genJob = await prisma.genJob.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GenJobs and only return the `id`
   * const genJobWithIdOnly = await prisma.genJob.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GenJobUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GenJobUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GenJob.
   * @param {GenJobUpsertArgs} args - Arguments to update or create a GenJob.
   * @example
   * // Update or create a GenJob
   * const genJob = await prisma.genJob.upsert({
   *   create: {
   *     // ... data to create a GenJob
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GenJob we want to update
   *   }
   * })
   */
  upsert<T extends GenJobUpsertArgs>(args: Prisma.SelectSubset<T, GenJobUpsertArgs<ExtArgs>>): Prisma.Prisma__GenJobClient<runtime.Types.Result.GetResult<Prisma.$GenJobPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GenJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobCountArgs} args - Arguments to filter GenJobs to count.
   * @example
   * // Count the number of GenJobs
   * const count = await prisma.genJob.count({
   *   where: {
   *     // ... the filter for the GenJobs we want to count
   *   }
   * })
  **/
  count<T extends GenJobCountArgs>(
    args?: Prisma.Subset<T, GenJobCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GenJobCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GenJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GenJobAggregateArgs>(args: Prisma.Subset<T, GenJobAggregateArgs>): Prisma.PrismaPromise<GetGenJobAggregateType<T>>

  /**
   * Group by GenJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GenJobGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GenJobGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GenJobGroupByArgs['orderBy'] }
      : { orderBy?: GenJobGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GenJobGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGenJobGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GenJob model
 */
readonly fields: GenJobFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GenJob.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GenJobClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  conversation<T extends Prisma.ConversationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConversationDefaultArgs<ExtArgs>>): Prisma.Prisma__ConversationClient<runtime.Types.Result.GetResult<Prisma.$ConversationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  message<T extends Prisma.GenJob$messageArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GenJob$messageArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GenJob model
 */
export interface GenJobFieldRefs {
  readonly id: Prisma.FieldRef<"GenJob", 'String'>
  readonly conversation_id: Prisma.FieldRef<"GenJob", 'String'>
  readonly message_id: Prisma.FieldRef<"GenJob", 'String'>
  readonly job_type: Prisma.FieldRef<"GenJob", 'AISkill'>
  readonly status: Prisma.FieldRef<"GenJob", 'GenJobStatus'>
  readonly provider: Prisma.FieldRef<"GenJob", 'String'>
  readonly model_id: Prisma.FieldRef<"GenJob", 'String'>
  readonly prompt: Prisma.FieldRef<"GenJob", 'String'>
  readonly aspect_ratio: Prisma.FieldRef<"GenJob", 'String'>
  readonly quality: Prisma.FieldRef<"GenJob", 'String'>
  readonly duration: Prisma.FieldRef<"GenJob", 'Int'>
  readonly fps: Prisma.FieldRef<"GenJob", 'Int'>
  readonly resolution: Prisma.FieldRef<"GenJob", 'String'>
  readonly extend_from_media_id: Prisma.FieldRef<"GenJob", 'String'>
  readonly extend_from_url: Prisma.FieldRef<"GenJob", 'String'>
  readonly extend_start_sec: Prisma.FieldRef<"GenJob", 'Float'>
  readonly result_url: Prisma.FieldRef<"GenJob", 'String'>
  readonly result_media_id: Prisma.FieldRef<"GenJob", 'String'>
  readonly error_message: Prisma.FieldRef<"GenJob", 'String'>
  readonly progress: Prisma.FieldRef<"GenJob", 'Int'>
  readonly started_at: Prisma.FieldRef<"GenJob", 'DateTime'>
  readonly completed_at: Prisma.FieldRef<"GenJob", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"GenJob", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"GenJob", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GenJob findUnique
 */
export type GenJobFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter, which GenJob to fetch.
   */
  where: Prisma.GenJobWhereUniqueInput
}

/**
 * GenJob findUniqueOrThrow
 */
export type GenJobFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter, which GenJob to fetch.
   */
  where: Prisma.GenJobWhereUniqueInput
}

/**
 * GenJob findFirst
 */
export type GenJobFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter, which GenJob to fetch.
   */
  where?: Prisma.GenJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GenJobs to fetch.
   */
  orderBy?: Prisma.GenJobOrderByWithRelationInput | Prisma.GenJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GenJobs.
   */
  cursor?: Prisma.GenJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GenJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GenJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GenJobs.
   */
  distinct?: Prisma.GenJobScalarFieldEnum | Prisma.GenJobScalarFieldEnum[]
}

/**
 * GenJob findFirstOrThrow
 */
export type GenJobFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter, which GenJob to fetch.
   */
  where?: Prisma.GenJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GenJobs to fetch.
   */
  orderBy?: Prisma.GenJobOrderByWithRelationInput | Prisma.GenJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GenJobs.
   */
  cursor?: Prisma.GenJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GenJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GenJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GenJobs.
   */
  distinct?: Prisma.GenJobScalarFieldEnum | Prisma.GenJobScalarFieldEnum[]
}

/**
 * GenJob findMany
 */
export type GenJobFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter, which GenJobs to fetch.
   */
  where?: Prisma.GenJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GenJobs to fetch.
   */
  orderBy?: Prisma.GenJobOrderByWithRelationInput | Prisma.GenJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GenJobs.
   */
  cursor?: Prisma.GenJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GenJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GenJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GenJobs.
   */
  distinct?: Prisma.GenJobScalarFieldEnum | Prisma.GenJobScalarFieldEnum[]
}

/**
 * GenJob create
 */
export type GenJobCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * The data needed to create a GenJob.
   */
  data: Prisma.XOR<Prisma.GenJobCreateInput, Prisma.GenJobUncheckedCreateInput>
}

/**
 * GenJob createMany
 */
export type GenJobCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GenJobs.
   */
  data: Prisma.GenJobCreateManyInput | Prisma.GenJobCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GenJob createManyAndReturn
 */
export type GenJobCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * The data used to create many GenJobs.
   */
  data: Prisma.GenJobCreateManyInput | Prisma.GenJobCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GenJob update
 */
export type GenJobUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * The data needed to update a GenJob.
   */
  data: Prisma.XOR<Prisma.GenJobUpdateInput, Prisma.GenJobUncheckedUpdateInput>
  /**
   * Choose, which GenJob to update.
   */
  where: Prisma.GenJobWhereUniqueInput
}

/**
 * GenJob updateMany
 */
export type GenJobUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GenJobs.
   */
  data: Prisma.XOR<Prisma.GenJobUpdateManyMutationInput, Prisma.GenJobUncheckedUpdateManyInput>
  /**
   * Filter which GenJobs to update
   */
  where?: Prisma.GenJobWhereInput
  /**
   * Limit how many GenJobs to update.
   */
  limit?: number
}

/**
 * GenJob updateManyAndReturn
 */
export type GenJobUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * The data used to update GenJobs.
   */
  data: Prisma.XOR<Prisma.GenJobUpdateManyMutationInput, Prisma.GenJobUncheckedUpdateManyInput>
  /**
   * Filter which GenJobs to update
   */
  where?: Prisma.GenJobWhereInput
  /**
   * Limit how many GenJobs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GenJob upsert
 */
export type GenJobUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * The filter to search for the GenJob to update in case it exists.
   */
  where: Prisma.GenJobWhereUniqueInput
  /**
   * In case the GenJob found by the `where` argument doesn't exist, create a new GenJob with this data.
   */
  create: Prisma.XOR<Prisma.GenJobCreateInput, Prisma.GenJobUncheckedCreateInput>
  /**
   * In case the GenJob was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GenJobUpdateInput, Prisma.GenJobUncheckedUpdateInput>
}

/**
 * GenJob delete
 */
export type GenJobDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
  /**
   * Filter which GenJob to delete.
   */
  where: Prisma.GenJobWhereUniqueInput
}

/**
 * GenJob deleteMany
 */
export type GenJobDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GenJobs to delete
   */
  where?: Prisma.GenJobWhereInput
  /**
   * Limit how many GenJobs to delete.
   */
  limit?: number
}

/**
 * GenJob.message
 */
export type GenJob$messageArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
}

/**
 * GenJob without action
 */
export type GenJobDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GenJob
   */
  select?: Prisma.GenJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GenJob
   */
  omit?: Prisma.GenJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GenJobInclude<ExtArgs> | null
}
