
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PuterSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PuterSession
 * 
 */
export type PuterSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$PuterSessionPayload>

export type AggregatePuterSession = {
  _count: PuterSessionCountAggregateOutputType | null
  _min: PuterSessionMinAggregateOutputType | null
  _max: PuterSessionMaxAggregateOutputType | null
}

export type PuterSessionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  token: string | null
  puter_username: string | null
  puter_uid: string | null
  app_uid: string | null
  is_valid: boolean | null
  validated_at: Date | null
  expires_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type PuterSessionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  token: string | null
  puter_username: string | null
  puter_uid: string | null
  app_uid: string | null
  is_valid: boolean | null
  validated_at: Date | null
  expires_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type PuterSessionCountAggregateOutputType = {
  id: number
  userId: number
  token: number
  puter_username: number
  puter_uid: number
  app_uid: number
  is_valid: number
  validated_at: number
  expires_at: number
  created_at: number
  updated_at: number
  _all: number
}


export type PuterSessionMinAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  puter_username?: true
  puter_uid?: true
  app_uid?: true
  is_valid?: true
  validated_at?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
}

export type PuterSessionMaxAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  puter_username?: true
  puter_uid?: true
  app_uid?: true
  is_valid?: true
  validated_at?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
}

export type PuterSessionCountAggregateInputType = {
  id?: true
  userId?: true
  token?: true
  puter_username?: true
  puter_uid?: true
  app_uid?: true
  is_valid?: true
  validated_at?: true
  expires_at?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type PuterSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PuterSession to aggregate.
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PuterSessions to fetch.
   */
  orderBy?: Prisma.PuterSessionOrderByWithRelationInput | Prisma.PuterSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PuterSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PuterSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PuterSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PuterSessions
  **/
  _count?: true | PuterSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PuterSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PuterSessionMaxAggregateInputType
}

export type GetPuterSessionAggregateType<T extends PuterSessionAggregateArgs> = {
      [P in keyof T & keyof AggregatePuterSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePuterSession[P]>
    : Prisma.GetScalarType<T[P], AggregatePuterSession[P]>
}




export type PuterSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PuterSessionWhereInput
  orderBy?: Prisma.PuterSessionOrderByWithAggregationInput | Prisma.PuterSessionOrderByWithAggregationInput[]
  by: Prisma.PuterSessionScalarFieldEnum[] | Prisma.PuterSessionScalarFieldEnum
  having?: Prisma.PuterSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PuterSessionCountAggregateInputType | true
  _min?: PuterSessionMinAggregateInputType
  _max?: PuterSessionMaxAggregateInputType
}

export type PuterSessionGroupByOutputType = {
  id: string
  userId: string
  token: string
  puter_username: string | null
  puter_uid: string | null
  app_uid: string | null
  is_valid: boolean
  validated_at: Date | null
  expires_at: Date | null
  created_at: Date
  updated_at: Date
  _count: PuterSessionCountAggregateOutputType | null
  _min: PuterSessionMinAggregateOutputType | null
  _max: PuterSessionMaxAggregateOutputType | null
}

export type GetPuterSessionGroupByPayload<T extends PuterSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PuterSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PuterSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PuterSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PuterSessionGroupByOutputType[P]>
      }
    >
  >



export type PuterSessionWhereInput = {
  AND?: Prisma.PuterSessionWhereInput | Prisma.PuterSessionWhereInput[]
  OR?: Prisma.PuterSessionWhereInput[]
  NOT?: Prisma.PuterSessionWhereInput | Prisma.PuterSessionWhereInput[]
  id?: Prisma.StringFilter<"PuterSession"> | string
  userId?: Prisma.StringFilter<"PuterSession"> | string
  token?: Prisma.StringFilter<"PuterSession"> | string
  puter_username?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  puter_uid?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  app_uid?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  is_valid?: Prisma.BoolFilter<"PuterSession"> | boolean
  validated_at?: Prisma.DateTimeNullableFilter<"PuterSession"> | Date | string | null
  expires_at?: Prisma.DateTimeNullableFilter<"PuterSession"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"PuterSession"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PuterSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PuterSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  puter_username?: Prisma.SortOrderInput | Prisma.SortOrder
  puter_uid?: Prisma.SortOrderInput | Prisma.SortOrder
  app_uid?: Prisma.SortOrderInput | Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  validated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PuterSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.PuterSessionWhereInput | Prisma.PuterSessionWhereInput[]
  OR?: Prisma.PuterSessionWhereInput[]
  NOT?: Prisma.PuterSessionWhereInput | Prisma.PuterSessionWhereInput[]
  token?: Prisma.StringFilter<"PuterSession"> | string
  puter_username?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  puter_uid?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  app_uid?: Prisma.StringNullableFilter<"PuterSession"> | string | null
  is_valid?: Prisma.BoolFilter<"PuterSession"> | boolean
  validated_at?: Prisma.DateTimeNullableFilter<"PuterSession"> | Date | string | null
  expires_at?: Prisma.DateTimeNullableFilter<"PuterSession"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"PuterSession"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PuterSession"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "puter_session_userId_unique">

export type PuterSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  puter_username?: Prisma.SortOrderInput | Prisma.SortOrder
  puter_uid?: Prisma.SortOrderInput | Prisma.SortOrder
  app_uid?: Prisma.SortOrderInput | Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  validated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  expires_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.PuterSessionCountOrderByAggregateInput
  _max?: Prisma.PuterSessionMaxOrderByAggregateInput
  _min?: Prisma.PuterSessionMinOrderByAggregateInput
}

export type PuterSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PuterSessionScalarWhereWithAggregatesInput | Prisma.PuterSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PuterSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PuterSessionScalarWhereWithAggregatesInput | Prisma.PuterSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PuterSession"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PuterSession"> | string
  token?: Prisma.StringWithAggregatesFilter<"PuterSession"> | string
  puter_username?: Prisma.StringNullableWithAggregatesFilter<"PuterSession"> | string | null
  puter_uid?: Prisma.StringNullableWithAggregatesFilter<"PuterSession"> | string | null
  app_uid?: Prisma.StringNullableWithAggregatesFilter<"PuterSession"> | string | null
  is_valid?: Prisma.BoolWithAggregatesFilter<"PuterSession"> | boolean
  validated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"PuterSession"> | Date | string | null
  expires_at?: Prisma.DateTimeNullableWithAggregatesFilter<"PuterSession"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"PuterSession"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"PuterSession"> | Date | string
}

export type PuterSessionCreateInput = {
  id?: string
  token: string
  puter_username?: string | null
  puter_uid?: string | null
  app_uid?: string | null
  is_valid?: boolean
  validated_at?: Date | string | null
  expires_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPuterSessionInput
}

export type PuterSessionUncheckedCreateInput = {
  id?: string
  userId: string
  token: string
  puter_username?: string | null
  puter_uid?: string | null
  app_uid?: string | null
  is_valid?: boolean
  validated_at?: Date | string | null
  expires_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type PuterSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPuterSessionNestedInput
}

export type PuterSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PuterSessionCreateManyInput = {
  id?: string
  userId: string
  token: string
  puter_username?: string | null
  puter_uid?: string | null
  app_uid?: string | null
  is_valid?: boolean
  validated_at?: Date | string | null
  expires_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type PuterSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PuterSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PuterSessionNullableScalarRelationFilter = {
  is?: Prisma.PuterSessionWhereInput | null
  isNot?: Prisma.PuterSessionWhereInput | null
}

export type PuterSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  puter_username?: Prisma.SortOrder
  puter_uid?: Prisma.SortOrder
  app_uid?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  validated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PuterSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  puter_username?: Prisma.SortOrder
  puter_uid?: Prisma.SortOrder
  app_uid?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  validated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PuterSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  token?: Prisma.SortOrder
  puter_username?: Prisma.SortOrder
  puter_uid?: Prisma.SortOrder
  app_uid?: Prisma.SortOrder
  is_valid?: Prisma.SortOrder
  validated_at?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PuterSessionCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PuterSessionCreateOrConnectWithoutUserInput
  connect?: Prisma.PuterSessionWhereUniqueInput
}

export type PuterSessionUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PuterSessionCreateOrConnectWithoutUserInput
  connect?: Prisma.PuterSessionWhereUniqueInput
}

export type PuterSessionUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PuterSessionCreateOrConnectWithoutUserInput
  upsert?: Prisma.PuterSessionUpsertWithoutUserInput
  disconnect?: Prisma.PuterSessionWhereInput | boolean
  delete?: Prisma.PuterSessionWhereInput | boolean
  connect?: Prisma.PuterSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PuterSessionUpdateToOneWithWhereWithoutUserInput, Prisma.PuterSessionUpdateWithoutUserInput>, Prisma.PuterSessionUncheckedUpdateWithoutUserInput>
}

export type PuterSessionUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PuterSessionCreateOrConnectWithoutUserInput
  upsert?: Prisma.PuterSessionUpsertWithoutUserInput
  disconnect?: Prisma.PuterSessionWhereInput | boolean
  delete?: Prisma.PuterSessionWhereInput | boolean
  connect?: Prisma.PuterSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PuterSessionUpdateToOneWithWhereWithoutUserInput, Prisma.PuterSessionUpdateWithoutUserInput>, Prisma.PuterSessionUncheckedUpdateWithoutUserInput>
}

export type PuterSessionCreateWithoutUserInput = {
  id?: string
  token: string
  puter_username?: string | null
  puter_uid?: string | null
  app_uid?: string | null
  is_valid?: boolean
  validated_at?: Date | string | null
  expires_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type PuterSessionUncheckedCreateWithoutUserInput = {
  id?: string
  token: string
  puter_username?: string | null
  puter_uid?: string | null
  app_uid?: string | null
  is_valid?: boolean
  validated_at?: Date | string | null
  expires_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type PuterSessionCreateOrConnectWithoutUserInput = {
  where: Prisma.PuterSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
}

export type PuterSessionUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PuterSessionUpdateWithoutUserInput, Prisma.PuterSessionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PuterSessionCreateWithoutUserInput, Prisma.PuterSessionUncheckedCreateWithoutUserInput>
  where?: Prisma.PuterSessionWhereInput
}

export type PuterSessionUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PuterSessionWhereInput
  data: Prisma.XOR<Prisma.PuterSessionUpdateWithoutUserInput, Prisma.PuterSessionUncheckedUpdateWithoutUserInput>
}

export type PuterSessionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PuterSessionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  puter_username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  puter_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  app_uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_valid?: Prisma.BoolFieldUpdateOperationsInput | boolean
  validated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expires_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PuterSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  puter_username?: boolean
  puter_uid?: boolean
  app_uid?: boolean
  is_valid?: boolean
  validated_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["puterSession"]>

export type PuterSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  puter_username?: boolean
  puter_uid?: boolean
  app_uid?: boolean
  is_valid?: boolean
  validated_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["puterSession"]>

export type PuterSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  token?: boolean
  puter_username?: boolean
  puter_uid?: boolean
  app_uid?: boolean
  is_valid?: boolean
  validated_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["puterSession"]>

export type PuterSessionSelectScalar = {
  id?: boolean
  userId?: boolean
  token?: boolean
  puter_username?: boolean
  puter_uid?: boolean
  app_uid?: boolean
  is_valid?: boolean
  validated_at?: boolean
  expires_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type PuterSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "token" | "puter_username" | "puter_uid" | "app_uid" | "is_valid" | "validated_at" | "expires_at" | "created_at" | "updated_at", ExtArgs["result"]["puterSession"]>
export type PuterSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PuterSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PuterSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PuterSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PuterSession"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    /**
     * JWT token dari puter.auth.signIn() — format: "eyJhbG..."
     * Disimpan encrypted menggunakan AES-256-GCM (sama seperti UserApiKey)
     */
    token: string
    /**
     * Username Puter user (e.g. "navy_river_8149")
     */
    puter_username: string | null
    /**
     * UUID Puter user (e.g. "0e7c654d-3db0-4be9-bd9c-50aa3b1a981a")
     */
    puter_uid: string | null
    /**
     * App UID dari Puter (e.g. "app-23924891-45b3-4190-b75e-dd72aadf3d30")
     */
    app_uid: string | null
    /**
     * Apakah token masih valid (invalidasi saat logout)
     */
    is_valid: boolean
    /**
     * Waktu token terakhir divalidasi ke Puter API
     */
    validated_at: Date | null
    /**
     * Waktu expired token (nullable — Puter token bisa long-lived)
     */
    expires_at: Date | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["puterSession"]>
  composites: {}
}

export type PuterSessionGetPayload<S extends boolean | null | undefined | PuterSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload, S>

export type PuterSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PuterSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PuterSessionCountAggregateInputType | true
  }

export interface PuterSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PuterSession'], meta: { name: 'PuterSession' } }
  /**
   * Find zero or one PuterSession that matches the filter.
   * @param {PuterSessionFindUniqueArgs} args - Arguments to find a PuterSession
   * @example
   * // Get one PuterSession
   * const puterSession = await prisma.puterSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PuterSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, PuterSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PuterSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PuterSessionFindUniqueOrThrowArgs} args - Arguments to find a PuterSession
   * @example
   * // Get one PuterSession
   * const puterSession = await prisma.puterSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PuterSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PuterSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PuterSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionFindFirstArgs} args - Arguments to find a PuterSession
   * @example
   * // Get one PuterSession
   * const puterSession = await prisma.puterSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PuterSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, PuterSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PuterSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionFindFirstOrThrowArgs} args - Arguments to find a PuterSession
   * @example
   * // Get one PuterSession
   * const puterSession = await prisma.puterSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PuterSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PuterSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PuterSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PuterSessions
   * const puterSessions = await prisma.puterSession.findMany()
   * 
   * // Get first 10 PuterSessions
   * const puterSessions = await prisma.puterSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const puterSessionWithIdOnly = await prisma.puterSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PuterSessionFindManyArgs>(args?: Prisma.SelectSubset<T, PuterSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PuterSession.
   * @param {PuterSessionCreateArgs} args - Arguments to create a PuterSession.
   * @example
   * // Create one PuterSession
   * const PuterSession = await prisma.puterSession.create({
   *   data: {
   *     // ... data to create a PuterSession
   *   }
   * })
   * 
   */
  create<T extends PuterSessionCreateArgs>(args: Prisma.SelectSubset<T, PuterSessionCreateArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PuterSessions.
   * @param {PuterSessionCreateManyArgs} args - Arguments to create many PuterSessions.
   * @example
   * // Create many PuterSessions
   * const puterSession = await prisma.puterSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PuterSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, PuterSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PuterSessions and returns the data saved in the database.
   * @param {PuterSessionCreateManyAndReturnArgs} args - Arguments to create many PuterSessions.
   * @example
   * // Create many PuterSessions
   * const puterSession = await prisma.puterSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PuterSessions and only return the `id`
   * const puterSessionWithIdOnly = await prisma.puterSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PuterSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PuterSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PuterSession.
   * @param {PuterSessionDeleteArgs} args - Arguments to delete one PuterSession.
   * @example
   * // Delete one PuterSession
   * const PuterSession = await prisma.puterSession.delete({
   *   where: {
   *     // ... filter to delete one PuterSession
   *   }
   * })
   * 
   */
  delete<T extends PuterSessionDeleteArgs>(args: Prisma.SelectSubset<T, PuterSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PuterSession.
   * @param {PuterSessionUpdateArgs} args - Arguments to update one PuterSession.
   * @example
   * // Update one PuterSession
   * const puterSession = await prisma.puterSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PuterSessionUpdateArgs>(args: Prisma.SelectSubset<T, PuterSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PuterSessions.
   * @param {PuterSessionDeleteManyArgs} args - Arguments to filter PuterSessions to delete.
   * @example
   * // Delete a few PuterSessions
   * const { count } = await prisma.puterSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PuterSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PuterSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PuterSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PuterSessions
   * const puterSession = await prisma.puterSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PuterSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, PuterSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PuterSessions and returns the data updated in the database.
   * @param {PuterSessionUpdateManyAndReturnArgs} args - Arguments to update many PuterSessions.
   * @example
   * // Update many PuterSessions
   * const puterSession = await prisma.puterSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PuterSessions and only return the `id`
   * const puterSessionWithIdOnly = await prisma.puterSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PuterSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PuterSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PuterSession.
   * @param {PuterSessionUpsertArgs} args - Arguments to update or create a PuterSession.
   * @example
   * // Update or create a PuterSession
   * const puterSession = await prisma.puterSession.upsert({
   *   create: {
   *     // ... data to create a PuterSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PuterSession we want to update
   *   }
   * })
   */
  upsert<T extends PuterSessionUpsertArgs>(args: Prisma.SelectSubset<T, PuterSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__PuterSessionClient<runtime.Types.Result.GetResult<Prisma.$PuterSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PuterSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionCountArgs} args - Arguments to filter PuterSessions to count.
   * @example
   * // Count the number of PuterSessions
   * const count = await prisma.puterSession.count({
   *   where: {
   *     // ... the filter for the PuterSessions we want to count
   *   }
   * })
  **/
  count<T extends PuterSessionCountArgs>(
    args?: Prisma.Subset<T, PuterSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PuterSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PuterSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PuterSessionAggregateArgs>(args: Prisma.Subset<T, PuterSessionAggregateArgs>): Prisma.PrismaPromise<GetPuterSessionAggregateType<T>>

  /**
   * Group by PuterSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PuterSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PuterSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PuterSessionGroupByArgs['orderBy'] }
      : { orderBy?: PuterSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PuterSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPuterSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PuterSession model
 */
readonly fields: PuterSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PuterSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PuterSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PuterSession model
 */
export interface PuterSessionFieldRefs {
  readonly id: Prisma.FieldRef<"PuterSession", 'String'>
  readonly userId: Prisma.FieldRef<"PuterSession", 'String'>
  readonly token: Prisma.FieldRef<"PuterSession", 'String'>
  readonly puter_username: Prisma.FieldRef<"PuterSession", 'String'>
  readonly puter_uid: Prisma.FieldRef<"PuterSession", 'String'>
  readonly app_uid: Prisma.FieldRef<"PuterSession", 'String'>
  readonly is_valid: Prisma.FieldRef<"PuterSession", 'Boolean'>
  readonly validated_at: Prisma.FieldRef<"PuterSession", 'DateTime'>
  readonly expires_at: Prisma.FieldRef<"PuterSession", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"PuterSession", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"PuterSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PuterSession findUnique
 */
export type PuterSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter, which PuterSession to fetch.
   */
  where: Prisma.PuterSessionWhereUniqueInput
}

/**
 * PuterSession findUniqueOrThrow
 */
export type PuterSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter, which PuterSession to fetch.
   */
  where: Prisma.PuterSessionWhereUniqueInput
}

/**
 * PuterSession findFirst
 */
export type PuterSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter, which PuterSession to fetch.
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PuterSessions to fetch.
   */
  orderBy?: Prisma.PuterSessionOrderByWithRelationInput | Prisma.PuterSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PuterSessions.
   */
  cursor?: Prisma.PuterSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PuterSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PuterSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PuterSessions.
   */
  distinct?: Prisma.PuterSessionScalarFieldEnum | Prisma.PuterSessionScalarFieldEnum[]
}

/**
 * PuterSession findFirstOrThrow
 */
export type PuterSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter, which PuterSession to fetch.
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PuterSessions to fetch.
   */
  orderBy?: Prisma.PuterSessionOrderByWithRelationInput | Prisma.PuterSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PuterSessions.
   */
  cursor?: Prisma.PuterSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PuterSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PuterSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PuterSessions.
   */
  distinct?: Prisma.PuterSessionScalarFieldEnum | Prisma.PuterSessionScalarFieldEnum[]
}

/**
 * PuterSession findMany
 */
export type PuterSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter, which PuterSessions to fetch.
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PuterSessions to fetch.
   */
  orderBy?: Prisma.PuterSessionOrderByWithRelationInput | Prisma.PuterSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PuterSessions.
   */
  cursor?: Prisma.PuterSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PuterSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PuterSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PuterSessions.
   */
  distinct?: Prisma.PuterSessionScalarFieldEnum | Prisma.PuterSessionScalarFieldEnum[]
}

/**
 * PuterSession create
 */
export type PuterSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a PuterSession.
   */
  data: Prisma.XOR<Prisma.PuterSessionCreateInput, Prisma.PuterSessionUncheckedCreateInput>
}

/**
 * PuterSession createMany
 */
export type PuterSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PuterSessions.
   */
  data: Prisma.PuterSessionCreateManyInput | Prisma.PuterSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PuterSession createManyAndReturn
 */
export type PuterSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * The data used to create many PuterSessions.
   */
  data: Prisma.PuterSessionCreateManyInput | Prisma.PuterSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PuterSession update
 */
export type PuterSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a PuterSession.
   */
  data: Prisma.XOR<Prisma.PuterSessionUpdateInput, Prisma.PuterSessionUncheckedUpdateInput>
  /**
   * Choose, which PuterSession to update.
   */
  where: Prisma.PuterSessionWhereUniqueInput
}

/**
 * PuterSession updateMany
 */
export type PuterSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PuterSessions.
   */
  data: Prisma.XOR<Prisma.PuterSessionUpdateManyMutationInput, Prisma.PuterSessionUncheckedUpdateManyInput>
  /**
   * Filter which PuterSessions to update
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * Limit how many PuterSessions to update.
   */
  limit?: number
}

/**
 * PuterSession updateManyAndReturn
 */
export type PuterSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * The data used to update PuterSessions.
   */
  data: Prisma.XOR<Prisma.PuterSessionUpdateManyMutationInput, Prisma.PuterSessionUncheckedUpdateManyInput>
  /**
   * Filter which PuterSessions to update
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * Limit how many PuterSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PuterSession upsert
 */
export type PuterSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the PuterSession to update in case it exists.
   */
  where: Prisma.PuterSessionWhereUniqueInput
  /**
   * In case the PuterSession found by the `where` argument doesn't exist, create a new PuterSession with this data.
   */
  create: Prisma.XOR<Prisma.PuterSessionCreateInput, Prisma.PuterSessionUncheckedCreateInput>
  /**
   * In case the PuterSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PuterSessionUpdateInput, Prisma.PuterSessionUncheckedUpdateInput>
}

/**
 * PuterSession delete
 */
export type PuterSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
  /**
   * Filter which PuterSession to delete.
   */
  where: Prisma.PuterSessionWhereUniqueInput
}

/**
 * PuterSession deleteMany
 */
export type PuterSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PuterSessions to delete
   */
  where?: Prisma.PuterSessionWhereInput
  /**
   * Limit how many PuterSessions to delete.
   */
  limit?: number
}

/**
 * PuterSession without action
 */
export type PuterSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PuterSession
   */
  select?: Prisma.PuterSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PuterSession
   */
  omit?: Prisma.PuterSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PuterSessionInclude<ExtArgs> | null
}
